### ISSUE TITLE
 How do I modify the display format of bold fonts？

### ISSUE THREAD

**Issue by songzenghui** [belenos/typora-solarized#1]
I think the bold fonts in the solarized-dark theme is not obvious,i want to change its format.Could you tell me how to modify it?By modifying *.css?
@belenos

**Comment by belenos** [comment]
Yeah, it makes sense. I'll update both themes to change the bold titles. 

But if you want to remove every bold font by yourself, feel free to edit the CSS files inside the themes folder (File > Preferences > Open Theme Folder) and change where it says _bold_ to _normal_.
